# conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/contacts-api
spring.datasource.username=postgres
spring.datasource.password=123456789

# driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# mostrar SQL no console (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
